### ISSUE TITLE
Allow Changing Sprite Color

### ISSUE THREAD

**Issue by zicklag** [fishfolk/bones#109]
We want you to be able to set the sprite "color" or "tint": the color the sprite pixels are multiplied by, which is pure white ( no change ) by default.

This should be a simple change.

We just need to add a `color` field to `Sprite` here:

https://github.com/fishfolk/bones/blob/632ef4e2d7647f6cb704a1b5eaeb2fbba9562314/crates/bones_render/src/sprite.rs#L20-L27

And we need to set the Bevy sprite color from the bones sprite color here:

https://github.com/fishfolk/bones/blob/632ef4e2d7647f6cb704a1b5eaeb2fbba9562314/crates/bones_bevy_renderer/src/lib.rs#L167-L168

**Comment by lecoqjacob** [comment]
I’ll take this!

**Comment by lecoqjacob** [comment]
This should be closed by #112
