### ISSUE TITLE
Can't Derive `TypeUlid` without adding it to `Cargo.toml`

### ISSUE THREAD

**Issue by zicklag** [fishfolk/bones#15]
The `TypeUlid` derive macro requires that you add the `type_ulid` crate to the `Cargo.toml`. We should fix that.

**Comment by varunpenumudi** [comment]
Hey i can fix fix that would you like to assign it to me

**Comment by zicklag** [comment]
Sure that'd be great, thanks!

**Comment by zicklag** [comment]
`type_ulid` isn't used by the bones ecosystem anymore, so it's softly unsupported, and it's basically feature-complete anyway.

I'm going to close this, but I'm still open to PRs to fix this if anybody happens to need it.
