### ISSUE TITLE
Non-game sessions(?) stops running during network match (after remote player input / rollback?)

### ISSUE THREAD

**Issue by MaxCWhitehead** [fishfolk/bones#336]
Context: I was testing the profiler PR for jumpy, I noticed that in networked game it didn't work reliably. I added some tracing, and it seems the  profiler session created in profiler game plugin stops running after remote player provides input. 

Repro:
1. Start two clients in networked game. Do not provide any input. Press F10 on one, one of them should successfully open profiler menu. (Or try F12 or other debug menus, profiler is not in main yet as of time writing this).
2. If you get menu open, provide input on other client, and it should close.
3. (Optional) Add a log statement into profiler system, to see that it stops running at this point.

I believe that when remote player gives input, the local player experiencing issue is having simulation state rolled back, which syncs an old clone of the World. I believe the way networking is saving / loading world is interfering with the way the Game loop modifies sessions / worlds to provide access to other sessions or shared resources. I have not dug into the details, but something seems to not work as intended, possibly on the networking side. (Right now we just clone and assign for syncing world).

Will look at this more when back from vacation if still an outstanding issue.

**Comment by zicklag** [comment]
That definitely doesn't sound right. Here's the spot where we run the game systems:

https://github.com/fishfolk/bones/blob/091c97883406be8a9ad2bb8683a114096afae23b/framework_crates/bones_lib/src/lib.rs#L292-L307

My only thought as to what would cause a game system to stop running is if that step function panicked or returned before the game systems got added back to the game here:

https://github.com/fishfolk/bones/blob/091c97883406be8a9ad2bb8683a114096afae23b/framework_crates/bones_lib/src/lib.rs#L417

**Comment by MaxCWhitehead** [comment]
I added this snippet to run during network rollback when loading the world again. The issue seems to be that before running a session we move and insert all of the other sessions into World as Sessions resource.
https://github.com/fishfolk/bones/blob/091c97883406be8a9ad2bb8683a114096afae23b/framework_crates/bones_lib/src/lib.rs#L350-L368

This means that the snapshot for networking includes other sessions by value. If we rollback to a snapshot before a session existed, it is destroyed. The profiler game plugin in this case only installs the session once, as after rolling back here it is gone.

This is kind of a special case, haven't thought deeply on solution yet but it feels like we shouldn't store the temporarily moved Sessions data as a resource on world. Perhaps the world should have a pointer to Game's Sessions, this way a rollback of world should not modify the actual data. Will test a fix.


I added this debug code and confirmed I saw this log indicating the network rollback destroyed the profiler session.
<img width="629" alt="image" src="https://github.com/fishfolk/bones/assets/35712032/bff845bf-fa1d-43d8-b8a9-7179146da4fd">

**Comment by MaxCWhitehead** [comment]
I'm seeing some very weird stuff trying to debug this - I did realize that Sessions has a UStrMap, I'm thinking this might be doing some evil magic, might be missing something but I found that the profiler session can disappear from Sessions just by doing this:

```
let sessions = world.resource::<Sessions>().deref().clone();
*world.resource_mut::<Sessions>() = sessions;
```

if I get profiler session from `world.resource::<Sessions>()` before and after clone + re-assignment, it's there before and gone after... It's also possible the way I access it for testing is the issue. I'm thinking that me doing `world.resource_mut::<Sessions>().get("profiler") as a str does not always produce the same hash, hence all the magic UStr claims to be doing. Maybe. Anyway this is getting silly, gonna revisit this after sleeping lol.

**Comment by zicklag** [comment]
> EDIT2: Oh, it's this:

Yeah... I wish there was a less _lying_ way to do that I guess, but I think it was the easiest solution and shouldn't hurt most people except for those who get into the weeds debugging something like this.

But that does explain what's happening now. When we rollback and restore a world snapshot, it overwrites the `Sessions` resource with a blank one, and that blank one then gets restored into the game here:

https://github.com/fishfolk/bones/blob/091c97883406be8a9ad2bb8683a114096afae23b/framework_crates/bones_lib/src/lib.rs#L357-L360

Maybe when we restore a snapshot, after cloning the snapshot world, we need to do a `mem::swap` on the `Sessions` resource to move it into the restored world, so that we don't lose it.

**Comment by MaxCWhitehead** [comment]
yeah I wish we could not implement clone but that doesn't work. Agreed on the pointer route.

Saving Sessions by swapping during load works, will open a PR.
