### ISSUE TITLE
Allow matchmaker to configure Iroh secret key for stable nodeID

### ISSUE THREAD

**Issue by MaxCWhitehead** [fishfolk/bones#405]
nodeID is derived from secret key which is currently randomly generated. Each time matchmaker restarts it will get a new node id, making it difficult to share a stable node ID (address for connection).

Couple of thoughts:

1. Could generate secret if not provided and save to a file (which would be some mounted volume on container, would need a write-able local path if non-containerized which is slightly more annoying).
2. Allow secret key (ed2515119) to be specified as env var, generate if none, otherwise use env.

I think two sounds slightly simpler / probably good enough.

**Comment by zicklag** [comment]
Yeah, I think option 2 is good. :+1:
