### ISSUE TITLE
Reduce transitive dependencies of `bones_schema`

### ISSUE THREAD

**Issue by zicklag** [fishfolk/bones#419]
I just added `bones_schema` to an empty project and realized that it's pulling in a lot it shouldn't need like `futures-lite` because that's included in `bones_utils`. We should probably aggressively feature-gate `bones_utils` dependencies, so that we can keep them wrapped up conveniently, but allow crates like `bones_schema` to only depend on the utilities that it needs.

**Comment by nelson137** [comment]
I've started to look into this. I began to make feature flags for all of the re-exported crates from `bones_utils` but I realized there may be a better direction to go in here. We could lift these deps to the root of the workspace and use the `<crate> = { workspace = true }` syntax in the libs that need them.

**Comment by MaxCWhitehead** [comment]
I think using workspace versions is a good idea +1
